descriptor-schema-version: "2.7"
info:
  name: iox-ir1101-dio-modbus
  version: latest
  description: Expose IR1101 DIO ports to Modbus TCP
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"
app:
  cpuarch: aarch64
  env:
    DEBIAN_FRONTEND: noninteractive
    HOME: /root
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    TERM: xterm
  resources:
    network:
    - interface-name: eth0
      ports: {}
    profile: c1.tiny
  startup:
    rootfs: rootfs.tar
    target:
    - bash
    - /idle.sh
    workdir: /root
  type: docker
